start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

default-root-container-layout = 'tiles'

default-root-container-orientation = 'horizontal'

automatically-unhide-macos-hidden-apps = true 

[key-mapping]
    preset = 'qwerty'

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-q = 'workspace 5'
    alt-w = 'workspace 6'
    alt-e = 'workspace 7'
    alt-r = 'workspace 8'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-q = 'move-node-to-workspace 5'
    alt-shift-w = 'move-node-to-workspace 6'
    alt-shift-e = 'move-node-to-workspace 7'
    alt-shift-r = 'move-node-to-workspace 8'

    [workspace-to-monitor-force-assignment]
        1 = 'main'
        2 = 'main'
        3 = 'main'
        4 = 'main'
        5 = ['secondary', 'main']
        6 = ['secondary', 'main']
        7 = ['secondary', 'main']
        8 = ['secondary', 'main']
