# Alacritty Configuration File (TOML format)

general.import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
# Font family and size
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 18.0

[keyboard]
bindings = [
  { key = "V", mods = "Alt", action = "ToggleViMode" }
]

[scrolling]
history = 100000
